'use client';
import {useEffect,useMemo,useState} from 'react';
import {motion,AnimatePresence} from 'framer-motion';
import {Check,ChevronDown,ChevronRight,Circle,Clock3,LockKeyhole,Play,RotateCcw,Route,Sparkles,TriangleAlert} from 'lucide-react';

type Status='todo'|'doing'|'blocked'|'done';
type Item={id:string;title:string;detail:string};
type Phase={id:string;kicker:string;title:string;goal:string;value:string;color:string;items:Item[]};
const phases:Phase[]=[
{id:'P0',kicker:'Fondations',title:'Un socle fiable',goal:'Sécuriser l’architecture avant d’accumuler les fonctionnalités.',value:'Une organisation isolée, authentifiée et déployable.',color:'#90b95b',items:[
{id:'P0.1',title:'Monorepo et frontières modulaires',detail:'Web Next.js, API NestJS, packages UI, domaine et configuration.'},{id:'P0.2',title:'Neon PostgreSQL, Prisma et migrations',detail:'Connexions poolée/directe, schéma multi-tenant, seed et sauvegardes.'},{id:'P0.3',title:'Authentification et sessions',detail:'Connexion sécurisée, récupération et préparation 2FA.'},{id:'P0.4',title:'Organisation, sites et RBAC',detail:'Permissions par module, boutique, caisse et action.'},{id:'P0.5',title:'Qualité et observabilité',detail:'CI, tests, OpenAPI, logs, erreurs et health checks.'}]},
{id:'P1',kicker:'Cœur produit',title:'La vérité du coût',goal:'Dire combien coûte réellement chaque produit, aujourd’hui.',value:'Coût unitaire traçable et impact d’une hausse de farine.',color:'#b7ef5b',items:[
{id:'P1.1',title:'Matières, unités et conversions',detail:'Sacs, kilogrammes, litres et règles exactes configurables.'},{id:'P1.2',title:'Achats, fournisseurs et lots',detail:'Réception, prix, stock et coût moyen pondéré.'},{id:'P1.3',title:'Recettes versionnées',detail:'Rendement, pertes prévues, emballage, énergie et main-d’œuvre.'},{id:'P1.4',title:'Moteur de coût théorique',detail:'Decimal, arrondis testés, prix minimum et marge cible.'},{id:'P1.5',title:'Production et coût réel',detail:'Consommation réelle, sorties, écarts et explications.'}]},
{id:'P2',kicker:'Opérations',title:'Vendre sans perdre',goal:'Relier chaque vente au stock, à la caisse et à la marge.',value:'Une vente offline synchronisée une seule fois.',color:'#f0c15c',items:[
{id:'P2.1',title:'Catalogue et tarifs',detail:'Produits, boutiques, promotions et permissions.'},{id:'P2.2',title:'POS et caisse',detail:'Ouverture, encaissement, clôture et contrôle.'},{id:'P2.3',title:'Offline robuste',detail:'IndexedDB, UUID, idempotence, reprise et conflits.'},{id:'P2.4',title:'Paiements',detail:'Espèces puis abstraction Mobile Money.'},{id:'P2.5',title:'Marge au moment de la vente',detail:'Sortie stock, coût de vente et audit immuable.'}]},
{id:'P3',kicker:'Décision',title:'Piloter chaque jour',goal:'Transformer les opérations en décisions simples.',value:'Ce qui s’est passé, pourquoi et quoi faire demain.',color:'#6fb5a0',items:[
{id:'P3.1',title:'Dashboard dirigeant',detail:'Ventes, coûts, marge, pertes, production et trésorerie.'},{id:'P3.2',title:'Alertes explicables',detail:'Cause, impact financier, confiance et action recommandée.'},{id:'P3.3',title:'Rapports automatiques',detail:'Synthèses quotidiennes et hebdomadaires exportables.'},{id:'P3.4',title:'Mode simple et expert',detail:'Vocabulaire adapté sans sacrifier la précision.'}]},
{id:'P4',kicker:'Finance',title:'Rentabilité défendable',goal:'Établir un résultat et une trésorerie contrôlables.',value:'P&L par produit et boutique, vérifiable par un expert.',color:'#d28b70',items:[
{id:'P4.1',title:'Dépenses et centres de coûts',detail:'Justificatifs, validation et ventilation.'},{id:'P4.2',title:'Créances, dettes et trésorerie',detail:'Échéances, prévisions et rapprochements.'},{id:'P4.3',title:'Budget et seuil de rentabilité',detail:'Objectifs, scénarios et écarts.'},{id:'P4.4',title:'Exports comptables',detail:'Journaux configurables et validation OHADA locale.'}]},
{id:'P5',kicker:'Échelle',title:'Plusieurs boutiques, une vérité',goal:'Consolider sans perdre la traçabilité locale.',value:'Vue groupe avec descente jusqu’au mouvement source.',color:'#899ad0',items:[
{id:'P5.1',title:'Entrepôts et transferts',detail:'Double validation, transit et réception.'},{id:'P5.2',title:'Consolidation multi-sites',detail:'Comparaison et rentabilité par boutique.'},{id:'P5.3',title:'Équipe et équipements',detail:'Présence, productivité, maintenance et énergie.'},{id:'P5.4',title:'B2B et livraison',detail:'Commandes, créances, tournées et preuves.'}]},
{id:'P6',kicker:'Intelligence',title:'Prévenir plutôt que constater',goal:'Recommander des actions mesurables et justifiées.',value:'Prévision, simulation et recommandations acceptées humainement.',color:'#b18bd0',items:[
{id:'P6.1',title:'Prévision de demande',detail:'Saisonnalité, événements et intervalle de confiance.'},{id:'P6.2',title:'Suggestions production et achat',detail:'Contraintes stock, capacité et durée de vie.'},{id:'P6.3',title:'Anomalies et simulations',detail:'Prix, pertes, caisse, énergie et scénarios.'},{id:'P6.4',title:'Copilote explicable',detail:'Sources, permissions, journalisation et validation humaine.'}]},
{id:'P7',kicker:'Croissance',title:'Monétiser par la valeur',goal:'Faire payer les gains créés, pas des limites artificielles.',value:'Un abonnement dont le ROI est démontré.',color:'#e2a35d',items:[
{id:'P7.1',title:'Plans et essais',detail:'Starter, Professional, Premium et Enterprise.'},{id:'P7.2',title:'ROI et paywall contextuel',detail:'Économies observées et valeur estimée.'},{id:'P7.3',title:'Billing et paiements',detail:'Abstraction fournisseur, factures et cycle de vie.'},{id:'P7.4',title:'Enterprise',detail:'API, SSO, audit avancé et intégrations.'}]},
];
const statusMeta={todo:{label:'À faire',icon:Circle,cls:'bg-[#eef0eb] text-[#687169]'},doing:{label:'En cours',icon:Play,cls:'bg-[#e5f4c9] text-[#507718]'},blocked:{label:'Bloqué',icon:TriangleAlert,cls:'bg-[#ffe5db] text-[#a34d3c]'},done:{label:'Terminé',icon:Check,cls:'bg-[#dff1e6] text-[#367153]'}};
const cycle:Status[]=['todo','doing','blocked','done'];
const baseline:Record<string,Status>={'P0.1':'done','P0.2':'blocked','P0.3':'doing','P0.4':'doing','P0.5':'done'};

export function ImplementationRoadmap(){
 const [statuses,setStatuses]=useState<Record<string,Status>>(baseline);
 const [open,setOpen]=useState<string>('P0');
 useEffect(()=>{try{const s=localStorage.getItem('boul.roadmap');if(s)setStatuses({...baseline,...JSON.parse(s)})}catch{}},[]);
 const update=(id:string,status:Status)=>{const n={...statuses,[id]:status};setStatuses(n);localStorage.setItem('boul.roadmap',JSON.stringify(n))};
 const all=phases.flatMap(p=>p.items),done=all.filter(x=>statuses[x.id]==='done').length,doing=all.filter(x=>statuses[x.id]==='doing').length;
 const progress=Math.round(done/all.length*100);
 return <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="p-4 md:p-7 max-w-[1350px] mx-auto">
  <div className="rounded-[28px] bg-[#18251c] text-white p-6 md:p-9 relative overflow-hidden">
   <div className="absolute inset-0 grid-fade opacity-30"/><div className="relative grid lg:grid-cols-[1.3fr_.7fr] gap-8 items-end">
    <div><span className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.15em] text-[#b7ef5b]"><Route size={13}/> Plan vivant · source versionnée</span><h2 className="text-3xl md:text-[42px] leading-[1.02] font-black tracking-[-.065em] mt-4 max-w-2xl">Construire la vérité financière, une tranche utile à la fois.</h2><p className="text-sm text-[#aab6ad] mt-4 max-w-2xl leading-6">Chaque incrément relie interface, API, données, permissions, audit et tests. Cliquez sur le statut d’une tâche pour piloter son avancement.</p></div>
    <div className="bg-white/[.06] border border-white/10 rounded-[22px] p-5 backdrop-blur"><div className="flex items-end"><span className="text-4xl font-black tracking-[-.06em]">{progress}%</span><span className="ml-auto text-[10px] text-[#a9b4ab] mb-1">{done}/{all.length} tâches</span></div><div className="h-2 rounded-full bg-white/10 mt-4 overflow-hidden"><motion.div animate={{width:`${progress}%`}} className="h-full bg-[#b7ef5b] rounded-full"/></div><div className="flex gap-3 mt-4 text-[10px]"><span className="flex items-center gap-1.5"><i className="w-2 h-2 bg-[#b7ef5b] rounded-full"/>{doing} en cours</span><span className="flex items-center gap-1.5 text-[#aab6ad]"><i className="w-2 h-2 bg-white/20 rounded-full"/>{all.length-done-doing} restantes</span></div></div>
   </div>
  </div>
  <div className="grid md:grid-cols-3 gap-3 mt-4"><Summary icon={LockKeyhole} label="Architecture" value="Monolithe modulaire" note="Extraction future sans complexité prématurée"/><Summary icon={Sparkles} label="Priorité métier" value="Coût de revient" note="Achat → stock → recette → marge"/><Summary icon={Clock3} label="Mode de livraison" value="Tranches verticales" note="Utilisable et testable à chaque incrément"/></div>
  <div className="mt-6 flex items-center justify-between"><div><h3 className="font-black text-xl tracking-[-.04em]">Parcours d’implémentation</h3><p className="text-[11px] text-[#7e887f] mt-1">Les dépendances vont de haut en bas.</p></div><button onClick={()=>{setStatuses(baseline);localStorage.removeItem('boul.roadmap')}} className="h-9 px-3 rounded-xl bg-white border border-[#dfe2db] text-[10px] font-bold flex items-center gap-2"><RotateCcw size={12}/>Réinitialiser</button></div>
  <div className="mt-4 space-y-3">{phases.map((phase,index)=>{const opened=open===phase.id;const phaseDone=phase.items.filter(i=>statuses[i.id]==='done').length;return <div key={phase.id} className="bg-white border border-[#e1e3dc] rounded-[22px] overflow-hidden"><button onClick={()=>setOpen(opened?'':phase.id)} className="w-full p-4 md:p-5 text-left flex items-center gap-4"><span className="w-11 h-11 rounded-2xl grid place-items-center font-black text-sm" style={{background:`${phase.color}28`,color:'#28342b'}}>{String(index).padStart(2,'0')}</span><div className="min-w-0"><div className="text-[9px] uppercase tracking-[.14em] font-bold text-[#879087]">{phase.kicker}</div><div className="font-black text-sm md:text-base mt-1">{phase.title}</div></div><div className="hidden md:block ml-auto mr-5 text-right"><div className="text-[10px] text-[#879087]">Progression</div><div className="text-xs font-black mt-1">{phaseDone}/{phase.items.length}</div></div><div className="w-8 h-8 rounded-xl bg-[#f2f4ef] grid place-items-center">{opened?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</div></button><AnimatePresence initial={false}>{opened&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden"><div className="border-t border-[#eceee8] p-4 md:p-5"><div className="grid md:grid-cols-2 gap-3 mb-5"><div className="rounded-2xl bg-[#f6f7f3] p-4"><div className="text-[9px] uppercase font-bold tracking-[.14em] text-[#89918a]">Objectif</div><p className="text-xs font-bold mt-2 leading-5">{phase.goal}</p></div><div className="rounded-2xl bg-[#eef6e7] p-4"><div className="text-[9px] uppercase font-bold tracking-[.14em] text-[#6d826b]">Preuve de sortie</div><p className="text-xs font-bold mt-2 leading-5">{phase.value}</p></div></div><div className="space-y-2">{phase.items.map(item=><Task key={item.id} item={item} status={statuses[item.id]||'todo'} onStatus={s=>update(item.id,s)}/>)}</div></div></motion.div>}</AnimatePresence></div>})}</div>
  <div className="mt-5 rounded-[22px] border border-[#e1e3dc] bg-[#f0f6e9] p-5 flex flex-col md:flex-row md:items-center gap-4"><div className="w-10 h-10 rounded-xl bg-[#dff0c8] grid place-items-center"><Play size={15}/></div><div><div className="text-[9px] uppercase tracking-[.14em] font-bold text-[#73816f]">Prochaine action recommandée</div><div className="font-black text-sm mt-1">P0.6 — Installer la CI qualité et sécurité</div></div><span className="md:ml-auto text-[10px] font-bold bg-white px-3 py-2 rounded-xl border border-white">Incrément I0</span></div>
 </motion.div>
}
function Summary({icon:Icon,label,value,note}:{icon:any;label:string;value:string;note:string}){return <div className="bg-white border border-[#e1e3dc] rounded-[18px] p-4"><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.13em] text-[#849087]"><Icon size={13}/>{label}</div><div className="text-sm font-black mt-3">{value}</div><div className="text-[10px] text-[#89928b] mt-1">{note}</div></div>}
function Task({item,status,onStatus}:{item:Item;status:Status;onStatus:(s:Status)=>void}){const meta=statusMeta[status],Icon=meta.icon;return <div className="flex flex-col md:flex-row md:items-center gap-3 p-3 rounded-2xl border border-[#eceee8] hover:border-[#d4d9d0] transition"><div className="w-10 h-10 shrink-0 rounded-xl bg-[#f4f5f1] grid place-items-center text-[10px] font-black">{item.id}</div><div className="min-w-0"><div className="text-xs font-bold">{item.title}</div><div className="text-[10px] text-[#879088] mt-1">{item.detail}</div></div><button onClick={()=>onStatus(cycle[(cycle.indexOf(status)+1)%cycle.length])} className={`md:ml-auto shrink-0 h-8 px-3 rounded-xl text-[10px] font-bold inline-flex items-center gap-2 ${meta.cls}`} title="Changer le statut"><Icon size={12}/>{meta.label}</button></div>}
